language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path=lzma-sys/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: doz50pX5K3fwF3q/imXgGMizUywODIzlJ49X78ofLhqKragSasYhqvQeg5nrIuCG6EjsYfD9UKoxjRAA/eOMQBXEMTqtypC13YjGflXu7zNdiNOjPu1VAK/Y8O+AxO7tahHaIgwABiu2P0sT8jOOpu2wy0SfTQUfEje7WiUtBTjqmFcQM7YBgfcDcrTXdKULljfJrj3fJdlB7wPx5dJkZiHpcdmY2q71OY8G9aicwe/i9eeC1PjjvXULrajn7ShGudLVRgI8omT9qRQtHoLcdHr0J42fST4lcK44qQmq+jfVsMF3S87FV5hpG/Ky0W8b65IqCtCpIO9wgjgrZ8NXavnBJ54CRNqaxy9FuOhxHUG/Z8eE5bdwjT2A7VCBdXasFFSnZO1jLgRbeWHiSqvljakCXO+ZFr20bYnEDOvDmMStPx48Y54ZpZ3SxdwV4pFi+/eXTpZixoESFxc80Sqd9kXL83in51sBZokFr0LpCQCRCeXKNu0D7N+RBuzBREQGA4vRP7qXh4EqDAojdDoknd0xL/oq69vxVWsjty8UHR9P0osNGqacMtZD+obPnS9YbZrMvTwqy5rw8DIF0YTUbc47KWxbySnV0snNhOQ40zHLjDCWwfeiLDmXQF7XQf4rz5ZVttmAl3GYFOHnSKH3TpxKes20hIbwYSEzTEClXJE=
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
