language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

# `liblzma-dev` comes preinstalled
#addons:
#    apt:
#      packages:
#      - liblzma-dev

matrix:
  exclude:
  - os: osx
    rust: beta
  - os: osx
    rust: nightly

before_script:
- if [[ $TRAVIS_OS_NAME = "linux" && $TRAVIS_RUST_VERSION = "nightly" && -n "$LZMA_API_STATIC" ]]; then
    pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH;
  fi

after_success:
- if [[ $TRAVIS_OS_NAME = "linux" && $TRAVIS_RUST_VERSION = "nightly" && -n "$LZMA_API_STATIC" ]]; then
    travis-cargo --only nightly doc-upload;
  fi

script:
  - cargo test
  - cargo test --features tokio
# `liblzma` on Ubuntu Trusty is older than we're linking and
# is missing a couple definitions that `systest` is looking for
  - if [[ -n "$LZMA_API_STATIC" ]]; then
      cargo run --manifest-path systest/Cargo.toml;
    fi
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path=lzma-sys/Cargo.toml

env:
  global:
    secure: "LgMtyKuSaQS4ovIeXJ5TxYaRGGgjjGGJIy8kgCc+8tcHnqpB4vP4cyBgO3wO+0E4EO4xD3j4isx+MgBRF0QN5uPdoZP66F7s2aHFlyr54mflp1CWpQE9mnb/1DxfAT3UqlR5Wv4vqyhsmnYWy2JqAZaHFLhGXkAEh9wbzvn7ssQL6yWJD2Siy2ReI5fAK26gNRqdtwd+Eli/CZAmx27FTkty4tXepTN94Y4ixOTmSpXRuSeAFLDCWrI7eydadKYBjFY7vpCXRWFpwVBem8hdItD82xJX0Bng0PPgmb3YNGVow4bciU6UsirlyueAONOIz5SC1VXwpkvbGl3b1XGZhnFIiN3h1Qc064P27KUtmyPO7Zs7enLmwbDXooRPqC64uxZUM/Y8X8vajo9pEM0uMPq33CEjN3u5uhJ/twoHixmXrpK+7XxQnfkm1klqM01GDABhIuZMKQcSgbnUx4G4FTTin/GUBsC09cEgsAp5Rgh7b1q6UfGryvF3MIehhnIAaoXr9MCjX6rV+KBrQu07uz+UY7NUJZcb4fvh6BxL0cAhOhWGz/QF1yAJWS1WNLyuJaB6Z5mhSuFkUoI73QDbJw4dBEWuLCOGBwXuV7++jdSq2kYOeQ8Momm48NKLWBK0KITAvoh2dHwihadV9P9AGGJFeuKP/utEX6CRkpV6y2Q="
  matrix:
    -
    - LZMA_API_STATIC=1

notifications:
  email:
    on_success: never
