language: rust
sudo: false

matrix:
  include:
    # stable/beta/nightly builds
    - rust: stable
    - rust: beta
    - rust: nightly

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
        - cargo doc --no-deps --manifest-path=lzma-sys/Cargo.toml
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master

    # bundled version works
    - env: LZMA_API_STATIC=1

    # OSX works as well, additionally with forced static build
    - os: osx
    - os: osx
      env: LZMA_API_STATIC=1

script:
  - cargo test
  - cargo test --features tokio
# `liblzma` on Ubuntu Trusty is older than we're linking and
# is missing a couple definitions that `systest` is looking for
  - if [[ -n "$LZMA_API_STATIC" ]]; then
      cargo run --manifest-path systest/Cargo.toml;
    fi

notifications:
  email:
    on_success: never
